import { StickerTemplate } from '../types';

export const DEFAULT_TEMPLATE: StickerTemplate = {
  id: 'a4-5x8-40',
  name: 'A4 5×8 (40 استيكر - 38 × 21 مم)',
  nameEn: 'A4 5×8 (40 Stickers - 38 × 21 mm)',
  description: 'قالب قياسي عام مرن - 40 استيكر في الورقة',
  isPreset: true,
  paperWidth: 210,
  paperHeight: 297,
  orientation: 'portrait',
  columns: 5,
  rows: 8,
  stickerWidth: 38,
  stickerHeight: 21,
  marginTop: 10,
  marginBottom: 10,
  marginLeft: 10,
  marginRight: 10,
  horizontalGap: 2,
  verticalGap: 2,
  fontFamily: 'Cairo',
  fontSize: 16,
  fontWeight: 'bold',
  italic: false,
  textColor: '#0f172a',
  backgroundColor: '#ffffff',
  textAlign: 'center',
  verticalAlign: 'middle',
  prefix: '',
  suffix: '',
  globalOffsetX: 0,
  globalOffsetY: 0,
  cornerRadiusMm: 1.5,
  flowDirection: 'rtl',
};

export const PRESET_TEMPLATES: StickerTemplate[] = [
  DEFAULT_TEMPLATE,
  {
    id: 'a4-3x8-24',
    name: 'A4 3×8 (24 استيكر - 64 × 33.8 مم)',
    nameEn: 'A4 3×8 (24 Stickers - 64 × 33.8 mm)',
    description: 'استيكرات متوسطة الحجم 24 في الورقة',
    isPreset: true,
    paperWidth: 210,
    paperHeight: 297,
    orientation: 'portrait',
    columns: 3,
    rows: 8,
    stickerWidth: 64,
    stickerHeight: 33.8,
    marginTop: 13.3,
    marginBottom: 13.3,
    marginLeft: 7,
    marginRight: 7,
    horizontalGap: 2,
    verticalGap: 0,
    fontFamily: 'Cairo',
    fontSize: 20,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 2,
  },
  {
    id: 'a4-4x8-32',
    name: 'A4 4×8 (32 استيكر - 48.5 × 25.4 مم)',
    nameEn: 'A4 4×8 (32 Stickers - 48.5 × 25.4 mm)',
    description: 'قالب 32 استيكر متوازن للملفات والأرقام',
    isPreset: true,
    paperWidth: 210,
    paperHeight: 297,
    orientation: 'portrait',
    columns: 4,
    rows: 8,
    stickerWidth: 48.5,
    stickerHeight: 25.4,
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 8,
    marginRight: 8,
    horizontalGap: 0,
    verticalGap: 0,
    fontFamily: 'Cairo',
    fontSize: 18,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 1.5,
  },
  {
    id: 'a4-3x7-21',
    name: 'A4 3×7 (21 استيكر - 70 × 38.1 مم)',
    nameEn: 'A4 3×7 (21 Stickers - 70 × 38.1 mm)',
    description: 'استيكرات واسعة للأرقام والأسماء أو الباركود',
    isPreset: true,
    paperWidth: 210,
    paperHeight: 297,
    orientation: 'portrait',
    columns: 3,
    rows: 7,
    stickerWidth: 70,
    stickerHeight: 38.1,
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 0,
    marginRight: 0,
    horizontalGap: 0,
    verticalGap: 0,
    fontFamily: 'Cairo',
    fontSize: 22,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 2,
  },
  {
    id: 'a4-2x7-14',
    name: 'A4 2×7 (14 استيكر - 105 × 42.4 مم)',
    nameEn: 'A4 2×7 (14 Stickers - 105 × 42.4 mm)',
    description: 'استيكرات كبيرة الحجم 14 في الورقة',
    isPreset: true,
    paperWidth: 210,
    paperHeight: 297,
    orientation: 'portrait',
    columns: 2,
    rows: 7,
    stickerWidth: 105,
    stickerHeight: 42.4,
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    horizontalGap: 0,
    verticalGap: 0,
    fontFamily: 'Cairo',
    fontSize: 26,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 2,
  },
  {
    id: 'a4-5x13-65',
    name: 'A4 5×13 (65 استيكر - 38.1 × 21.2 مم مصغر)',
    nameEn: 'A4 5×13 (65 Mini Stickers - 38.1 × 21.2 mm)',
    description: 'استيكرات صغيرة كثيفة لترقيم سريع',
    isPreset: true,
    paperWidth: 210,
    paperHeight: 297,
    orientation: 'portrait',
    columns: 5,
    rows: 13,
    stickerWidth: 38.1,
    stickerHeight: 21.2,
    marginTop: 10.7,
    marginBottom: 10.7,
    marginLeft: 4.7,
    marginRight: 4.7,
    horizontalGap: 2.5,
    verticalGap: 0,
    fontFamily: 'Cairo',
    fontSize: 14,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 1,
  },
  {
    id: 'a5-2x5-10',
    name: 'A5 2×5 (10 استيكرات - 65 × 38 مم) [ورقة A5 صغيرة]',
    nameEn: 'A5 2×5 (10 Stickers - 65 × 38 mm) [Small A5 Sheet]',
    description: 'ورقة A5 (أصغر من A4) - 10 استيكرات مقاس 65×38 مم',
    isPreset: true,
    paperWidth: 148,
    paperHeight: 210,
    orientation: 'portrait',
    columns: 2,
    rows: 5,
    stickerWidth: 65,
    stickerHeight: 38,
    marginTop: 7,
    marginBottom: 7,
    marginLeft: 7,
    marginRight: 7,
    horizontalGap: 4,
    verticalGap: 1.5,
    fontFamily: 'Cairo',
    fontSize: 18,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 1.5,
  },
  {
    id: 'a5-3x7-21',
    name: 'A5 3×7 (21 استيكر - 44 × 25.4 مم) [ورقة A5 صغيرة]',
    nameEn: 'A5 3×7 (21 Stickers - 44 × 25.4 mm) [Small A5 Sheet]',
    description: 'ورقة A5 (أصغر من A4) - 21 استيكر مقاس 44×25.4 مم',
    isPreset: true,
    paperWidth: 148,
    paperHeight: 210,
    orientation: 'portrait',
    columns: 3,
    rows: 7,
    stickerWidth: 44,
    stickerHeight: 25.4,
    marginTop: 12,
    marginBottom: 12,
    marginLeft: 5,
    marginRight: 5,
    horizontalGap: 3,
    verticalGap: 1.5,
    fontFamily: 'Cairo',
    fontSize: 15,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 1.5,
  },
  {
    id: 'a5-4x6-24',
    name: 'A5 4×6 (24 استيكر - 32 × 30 مم) [ورقة A5 صغيرة]',
    nameEn: 'A5 4×6 (24 Stickers - 32 × 30 mm) [Small A5 Sheet]',
    description: 'ورقة A5 (أصغر من A4) - 24 استيكر مصغر مقاس 32×30 مم',
    isPreset: true,
    paperWidth: 148,
    paperHeight: 210,
    orientation: 'portrait',
    columns: 4,
    rows: 6,
    stickerWidth: 32,
    stickerHeight: 30,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 6,
    marginRight: 6,
    horizontalGap: 2.5,
    verticalGap: 2,
    fontFamily: 'Cairo',
    fontSize: 14,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 1.5,
  },
  {
    id: 'custom-template',
    name: 'قالب مخصص (أدخل المقاسات يدوياً)',
    nameEn: 'Custom Template (Manual Dimensions)',
    description: 'خصص أبعاد الورقة والاستيكر والهوامش بدقة كاملة',
    isPreset: true,
    paperWidth: 210,
    paperHeight: 297,
    orientation: 'portrait',
    columns: 5,
    rows: 8,
    stickerWidth: 38,
    stickerHeight: 21,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    horizontalGap: 2,
    verticalGap: 2,
    fontFamily: 'Cairo',
    fontSize: 16,
    fontWeight: 'bold',
    italic: false,
    textColor: '#0f172a',
    backgroundColor: '#ffffff',
    textAlign: 'center',
    verticalAlign: 'middle',
    prefix: '',
    suffix: '',
    globalOffsetX: 0,
    globalOffsetY: 0,
    cornerRadiusMm: 1.5,
  }
];
